name: flutter_single_instance
description: >-
  This package provides a simple way to check if your application is already running.  You  can use this to prevent multiple instances of your application from running at the same time.


version: 1.1.1
repository: https://github.com/necodeIT/flutter_single_instance
platforms:
  linux:
  macos:
  windows:

environment:
  sdk: ">=2.16.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.13

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
